deck:
    -   id: 1
        type: 1
        title: Visa Card
        description: Visa credit card

    -   id: 2
        type: 2
        title: Mastercard
        description: Mastercard debit card

    -   id: 3
        type: 3
        title: Amex Card
        description: American Express charge card
